# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: IgorPavlov.7-Zip
PackageVersion: 21.07
InstallerSwitches:
  Silent: 1
  SilentWithProgress: 1
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://www.7-zip.org/a/7z2107-x64.exe
  InstallerSha256: 0B461F0A0ECCFC4F39733A80D70FD1210FDD69F600FB6B657E03940A734E5FC1
ManifestType: installer
ManifestVersion: 1.1.0

